# -*- coding: utf-8 -*-
"""TASK 4: Object Detection and Tracking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bN5Y6Bk_j6v9gIe6gYAzA5tgULS8Et-s
"""

!pip install ultralytics
!pip install opencv-python
!pip install filterpy
!pip install lap

import cv2
import numpy as np
from ultralytics import YOLO
from google.colab.patches import cv2_imshow

model = YOLO("yolov8n.pt")

!wget -O video.mp4 "https://github.com/intel-iot-devkit/sample-videos/raw/master/person-bicycle-car-detection.mp4"

video_path = "video.mp4"

cap = cv2.VideoCapture(video_path)

width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(cap.get(cv2.CAP_PROP_FPS))

fourcc = cv2.VideoWriter_fourcc(*'mp4v')

out = cv2.VideoWriter(
    'output.mp4',
    fourcc,
    fps,
    (width, height)
)

frame_count = 0

while cap.isOpened():

    success, frame = cap.read()

    if not success:
        print("Finished processing video.")
        break

    results = model.track(
        frame,
        persist=True,
        conf=0.5
    )

    annotated_frame = results[0].plot()

    out.write(annotated_frame)

    frame_count += 1

    if frame_count % 30 == 0:
        print(f"Processed {frame_count} frames")

cap.release()
out.release()

cv2.destroyAllWindows()

print("Output video saved as output.mp4")

import os

print(os.path.exists("output.mp4"))

from google.colab import files

files.download("output.mp4")

